ControleDeEstoqueCPM/ControleDeEstoqueCPM/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleDeEstoqueCPM.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage ="Informe o Usuario")]
        [Display(Name = "Usuário:")]
        public string Usuario { get; set; }
        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha:")]
        public string Senha { get; set; }
        [Display(Name = "LEmbrar-me:")]
        public bool LembrarMe { get; set; }
    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoqueCPM.Controllers
{
    public class CadastroController : Controller
    {
      [Authorize]
        public ActionResult GrupoProduto()
        {
            return View();

        }
        [Authorize]
        public ActionResult Marcaproduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Localproduto()
        {
            return View();
        }
        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }
        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }
        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }
        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }
        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }
        [Authorize]
        public ActionResult Fornecedor()
        {
            return View();
        }
        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }
        [Authorize]
        public ActionResult Usuario()
        {
            return View();
        }
    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/ContaController.cs
using ControleDeEstoqueCPM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleDeEstoqueCPM.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);
            }
            var achou = login.Usuario == "Diogo" && login.Senha == "123";

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login Invalido");
            }
            return View(login);
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoqueCPM.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        [Authorize]
        public ActionResult PerdasMes()
        {
            return View();
        }
        [Authorize]
        public ActionResult EntradaSaidaMensal()
        {
            return View();
        }
    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoqueCPM.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoqueCPM.Controllers
{
    public class OperacaoController : Controller
    {
        // GET: Operacao
        [Authorize]
        public ActionResult EntradaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult SaidaEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult LancPerdasProdutos()
        {
            return View();
        }
        [Authorize]
        public ActionResult Inventario()
        {
            return View();
        }
    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Controllers/RelatoriosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoqueCPM.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: Relatorios
        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        [Authorize]
        public ActionResult Ressuprimento()
        {
            return View();
        }
    }
}

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Grafico/EntradaSaidaMensal.cshtml
@{
    ViewBag.Title = "EntradaSaidaMensal";
}

<h2>EntradaSaidaMensal</h2>

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Grafico/PerdasMes.cshtml
@{
    ViewBag.Title = "PerdasMes";
}

<h2>PerdasMes</h2>

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title O Controle de Estoque</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Relatorio/PosicaoEstoque.cshtml
@{
    ViewBag.Title = "PosicaoEstoque";
}

<h2>PosicaoEstoque</h2>

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Relatorio/Ressuprimento.cshtml
@{
    ViewBag.Title = "Ressuprimento";
}

<h2>Ressuprimento</h2>

ControleDeEstoqueCPM/ControleDeEstoqueCPM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav ">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastros
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupos de Produtos", "GrupoProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Marcas de Produtos", "Marcaproduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Locais de Armazenamento", "Localproduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de medida", "UnidadeMedida", "Cadastro")</li>
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li class=" nav-divider"></li>
                                <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                                <li class=" nav-divider"></li>
                                <li>@Html.ActionLink("Perfis de usuario", "PerfilUsuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Usuarios", "Usuario", "Cadastro")</li>
                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de Produtos", "EntradaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Saída de produtos", "SaidaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Lançamento de perdas de Produtos", "LancPerdasProdutos", "Operacao")</li>
                                <li>@Html.ActionLink("Inventario de Estoque", "Inventario", "Operacao")</li>
                            </ul>

                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relátorios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posicao do Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>
                            </ul>

                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por Mês", "PerdasMes", "Grafico")</li>
                                <li>@Html.ActionLink("Entrdas vd saídas por mês ", "EntradaSaidaMensal", "Grafico")</li>
                            </ul>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                        <li><a href="#">Olá @User.Identity.Name</a></li>
                        @using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                        {
                            <li>
                                <a href="javascript:document.getElementById('logoffForm').submit()">sair</a>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de estoque Como Programar melhor.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>